version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile

    image: devcontainer-base:latest

    # Container name
    container_name: devcontainer-${PROJECT_NAME:-base}

    # Volumes
    volumes:
      # Workspace mount
      - ../..:/workspace:cached

      # Persistent volumes
      - devcontainer-history:/home/developer/.history
      - devcontainer-extensions:/home/developer/.vscode-server/extensions

      # Optional: Mount SSH keys (uncomment if needed)
      # - ~/.ssh:/home/developer/.ssh-host:ro

      # Optional: Mount git config (uncomment if needed)
      # - ~/.gitconfig:/home/developer/.gitconfig-host:ro

    # Working directory
    working_dir: /workspace

    # Command (keep container running)
    command: sleep infinity

    # Environment variables
    environment:
      - TZ=UTC
      - CLAUDE_CODE_CONTAINER=true
      - PROJECT_ROOT=/workspace

    # User
    user: developer

    # Network
    network_mode: bridge

    # Port forwarding (override per project)
    # ports:
    #   - "3000:3000"
    #   - "8000:8000"

    # Restart policy
    restart: unless-stopped

    # Resource limits (optional)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 4G

volumes:
  devcontainer-history:
    name: devcontainer-history-${PROJECT_NAME:-base}
  devcontainer-extensions:
    name: devcontainer-extensions-${PROJECT_NAME:-base}
