# Prometheus Configuration
# Metrics collection and storage for VPS monitoring

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    cluster: 'vps'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
      timeout: 10s
      api_version: v2

# Load alert rules
rule_files:
  - '/etc/prometheus/alerts.yml'

# Scrape configurations
scrape_configs:
  # ============================================================================
  # Prometheus self-monitoring
  # ============================================================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # ============================================================================
  # Node Exporter - System Metrics
  # ============================================================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'
          instance: 'vps'

  # ============================================================================
  # cAdvisor - Container Metrics
  # ============================================================================
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'

  # ============================================================================
  # Alertmanager
  # ============================================================================
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
        labels:
          service: 'alertmanager'

  # ============================================================================
  # Grafana
  # ============================================================================
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          service: 'grafana'

  # ============================================================================
  # Loki
  # ============================================================================
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          service: 'loki'

  # ============================================================================
  # PostgreSQL Exporter (if enabled)
  # ============================================================================
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
    # Only scrape if postgres-exporter is running
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres-exporter:9187

  # ============================================================================
  # Redis Exporter (if enabled)
  # ============================================================================
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  # ============================================================================
  # Nginx Exporter (if enabled)
  # ============================================================================
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'nginx'

  # ============================================================================
  # Celery Exporter (if enabled)
  # ============================================================================
  - job_name: 'celery'
    static_configs:
      - targets: ['celery-exporter:9808']
        labels:
          service: 'celery'

  # ============================================================================
  # Application Metrics (FastAPI, Next.js)
  # ============================================================================
  - job_name: 'app-metrics'
    static_configs:
      - targets: []  # Add your application metrics endpoints here
        # Example:
        # - 'fastapi-app:8000'
        # - 'nextjs-app:3000'
    # Service discovery for Docker containers
    # Uncomment if using Docker SD
    # docker_sd_configs:
    #   - host: unix:///var/run/docker.sock
    #     refresh_interval: 30s
    # relabel_configs:
    #   - source_labels: [__meta_docker_container_label_monitoring]
    #     regex: 'true'
    #     action: keep
    #   - source_labels: [__meta_docker_container_name]
    #     target_label: container
    #   - source_labels: [__meta_docker_container_label_com_docker_compose_service]
    #     target_label: service

  # ============================================================================
  # Blackbox Exporter - Endpoint Monitoring (if needed)
  # ============================================================================
  # - job_name: 'blackbox'
  #   metrics_path: /probe
  #   params:
  #     module: [http_2xx]
  #   static_configs:
  #     - targets:
  #         - https://example.com
  #         - https://api.example.com
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: blackbox-exporter:9115
